# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LDX_SwiftBase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LDX_SwiftBase
pod 'Kingfisher'
pod 'Alamofire', '~> 4.4'
pod 'KYCircularProgress'
pod 'SnapKit'
pod 'GrowingTextView’
pod 'SwiftyJSON’
pod 'JQProgressHUD’
pod 'MJRefresh’
pod 'SVProgressHUD’
pod 'RxSwift'
pod 'RxCocoa'
pod 'HMSegmentedControl'
pod 'Then'
pod 'Moya'
pod 'Reusable'
pod 'IQKeyboardManagerSwift'
pod 'SDWebImage'
pod 'Spring'
pod 'UITableView+FDTemplateLayoutCell'
pod 'MJExtension'
pod 'AFNetworking'


end
